language: python
python:
  - "2.7"

install:
  - pip install pep8
  - pip install conda
  - conda create -y -n newenv numba
  - source activate newenv
  - pip install futures

script:
  - pep8 .
  - ./test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)

